### ISSUE TITLE
changes not saving

### ISSUE THREAD

**Issue by crmackay** [open-source-society/ossu-client#23]
After logging out, and logging back in after a few minutes, the changes to my course record don't seem to be saving.

Don't have a chance to add more details right now, but let me know if you need more details

**Comment by SergeyKhval** [comment]
@crmackay couldn't reproduce this bug. are there any errors in web console?

**Comment by crmackay** [comment]
so steps to reproduce:
- go to `/#/account`
- change a course to "In progress"
- press save (and save icon appears)
- refresh browser 
- click "logout"
- refresh browser
- click "login with github"
- the change is missing


I don not see any output on the js console, or any other browser errors...

**Comment by SergeyKhval** [comment]
What browser and its version are you using?

**Comment by crmackay** [comment]
chrome 49.0.2623.110 (64-bit)

osx 10.11.2

**Comment by crmackay** [comment]
ok so it appears that the "login" step clears any changes saved to the default/empty curriculum.

I can make and save changes and view them on my profile page (`#/profile/github:3801862`), and these saved changes are viewable on other devices. They remain visible after I click "logout".

As soon as I click "login" again, the changes are cleared, and I have a blank curriculum again.

So it appears that the "Login with Github" step automatically creates a blank curriculum, where it should first check to see if a curriculum already exists (or if the user has previously logged in, etc.)

**Comment by crmackay** [comment]
ok another clue:

I think it has to do with [this line](https://github.com/open-source-society/ossu-client/blob/5eb87e97cf4ae3e60cb6c7dc46828162d50fa589/app/scripts/services/user.js#L23)

```javascript
if (!profile.email) {
            $q.all(courseArr.map(function (course) {
              var courseId = course.$id,
                courseTitle = course.title,
                courseLink = course.link,
                courseCat = course.category,
                courseRef = $firebaseObject(Ref.child('profiles').child(uid).child('courses').child(courseId));

```

my account doesn't have a public email associated with it...

**Comment by SergeyKhval** [comment]
Yeah, that's for sure a case. Thanks for your help.

**Comment by SergeyKhval** [comment]
deployed
