### ISSUE TITLE
Fix "home" link in footer

### ISSUE THREAD

**Issue by ericdouglas** [open-source-society/ossu-client#35]
When I click in the `home`link in footer, I get that screen in the URL `https://ossu.firebaseapp.com/#`. 

The correct URL should be `https://ossu.firebaseapp.com/#/`

![home bug](http://i.imgur.com/xug5Hwk.png)

**Comment by SergeyKhval** [comment]
Fixed it with this commit 6e44b1713400b294b933bffa0caf63665a85ba5d
