### ISSUE TITLE
Update curriculum to version 3.0.0

### ISSUE THREAD

**Issue by ericdouglas** [open-source-society/ossu-client#42]
Update the curriculum to [version 3.0.0](https://github.com/open-source-society/computer-science/issues/316).

**Comment by SergeyKhval** [comment]
I suppose this is a top priority now. This change will affect only newly suscriing users, as the curriculum is copied into user profile

**Comment by ericdouglas** [comment]
@SergeyKhval ok, no problem :smile:

**Comment by SergeyKhval** [comment]
fixed ece64cb

**Comment by SergeyKhval** [comment]
deployed

**Comment by ericdouglas** [comment]
@SergeyKhval , perfect! :ok_hand: :clap:
