### ISSUE TITLE
Current course does not appear in web app.

### ISSUE THREAD

**Issue by bandarr** [open-source-society/ossu-client#49]
I'm currently enrolled in CS50x, but it does not show up in the web app:

![image](https://cloud.githubusercontent.com/assets/18521413/16019671/1794ce4e-3178-11e6-99eb-1943d604ad8e.png)

I registered quite a while ago, before the 3.0 upgrade.   I would like to be "transferred" to the 3.0 curriculum.

**Comment by SergeyKhval** [comment]
Hello, @bandarr 
There was a recent update which allows to reset progress and download the latest version of curriculum. Please head over to your profile on OSSU and hit 'Reset progress' button
