### ISSUE TITLE
Order of Courses is Wrong

### ISSUE THREAD

**Issue by srs1978** [open-source-society/ossu-client#52]
I did not check the entire order, but CS50 came in as the last course.

While this happened to me after using the data scrub feature, I verified using my work GitHub account that it seems to affect all users.

**Comment by SergeyKhval** [comment]
Yeah, seems like new courses are at the bottom of the list.

**Comment by srs1978** [comment]
I changed the actual issue since it's unrelated to the data scrub feature at all.

**Comment by srs1978** [comment]
Since issues client is dead ...
