### ISSUE TITLE
Profile lists all courses as completed.

### ISSUE THREAD

**Issue by samfrances** [open-source-society/ossu-client#54]
My profile on the firebase apps lists all courses under "Finished courses". This doesn't seem likely to be the desired behaviour - I haven't recorded any progress at all yet.

My profile: https://ossu.firebaseapp.com/#/profile/github:2003369

**Comment by ericdouglas** [comment]
@samfrances 

We now have a new way to track our progress. Please, read [this section](https://github.com/open-source-society/computer-science#how-to-track-and-show-your-progress) to understand how it will be done.

Many thanks and sorry for the inconvenience. :smile:
