### ISSUE TITLE
Theory/Automata is deprecated

### ISSUE THREAD

**Issue by lubien** [open-source-society/ossu-client#56]
It send us to this [link](https://www.coursera.org/browse?languages=pt&source=deprecated_spark_cdp)

**Comment by ericdouglas** [comment]
We need to update the curriculum to v5.0.0. It'll be done ASAP.

**Comment by ericdouglas** [comment]
@lubien 

We now have a new way to track our progress. Please, read [this section](https://github.com/open-source-society/computer-science#how-to-track-and-show-your-progress) to understand how it will be done.

Many thanks and sorry for the inconvenience. :smile:

**Comment by lubien** [comment]
Thank you ^^
