### ISSUE TITLE
Some links need to be updated in Curriculum page

### ISSUE THREAD

**Issue by ericdouglas** [open-source-society/ossu-client#57]
More information [here](https://github.com/open-source-society/computer-science/issues/366)

**Comment by hugohonda** [comment]
this one also: https://www.coursera.org/learn/intro-to-big-data

**Comment by andy5995** [comment]
And this: [Natural Language Processing](https://www.coursera.org/course/nlangp)

**Comment by ericdouglas** [comment]
@hugohonda @andy5995 

We now have a new way to track our progress. Please, read [this section](https://github.com/open-source-society/computer-science#how-to-track-and-show-your-progress) to understand how it will be done.

Many thanks and sorry for the inconvenience. :smile:
