### ISSUE TITLE
Changes not saved

### ISSUE THREAD

**Issue by awahhab** [open-source-society/ossu-client#58]
When I logout and login again, all my changes (progress & links to repos) is removed.
I found this old closed issue about the same problem:
https://github.com/open-source-society/ossu-client/issues/23

I noticed that if I check my public profile after logout, it is fine. the reset happens only when I login again.

**Comment by ericdouglas** [comment]
@awahhab did you follow [these steps](https://github.com/open-source-society/computer-science/issues/362#issuecomment-250978347)?

Because here everything is working fine.

If you're still facing some problems, could you please try to see if you get some error in the console of the browser?

**Comment by awahhab** [comment]
Yes I followed exactly all the steps. and no errors in the browser console.
I tried different browsers (Chrome, FF, Edge) on Windows 10 46-bit

**Comment by astrotee** [comment]
did the same steps and there is no errors in the console

**Comment by ericdouglas** [comment]
@awahhab @astrotee 

We now have a new way to track our progress. Please, read [this section](https://github.com/open-source-society/computer-science#how-to-track-and-show-your-progress) to understand how it will be done.

Many thanks and sorry for the inconvenience. :smile:
