### ISSUE TITLE
Can't change profile name or avatar

### ISSUE THREAD

**Issue by elbrand** [open-source-society/ossu-client#60]
There is currently no way to change your profile name or avatar because once the profile exists, those never update. Name and avatar should always match github account.

**Comment by ericdouglas** [comment]
@elbrand 

We now have a new way to track our progress. Please, read [this section](https://github.com/open-source-society/computer-science#how-to-track-and-show-your-progress) to understand how it will be done.

Many thanks and sorry for the inconvenience. :smile:
